import Head from 'next/head'
import Header from '../src/components/Header'
import Labeling from '../src/devices/Labeling'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Labeling/>
      </main>
    </div>
  )
}
