import Head from 'next/head'
import { PipelineBuilder } from '../src/utils/Pipeline';
import { useState } from 'react'
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';

import styles from '../styles/Home.module.css'
import Header from '../src/components/Header';
import { Container } from 'react-bootstrap';

export default function Playground() {
  const [base64, setBase64] = useState("");
  const clicked = async () => {
    const state = { base64 }
    const pipeline = await PipelineBuilder.loadFromPath("/configs/abbott.json")
    const { result, reason } = await pipeline.execute(state);
    if (result) {
      const inputContext = document.getElementById('input-canvas').getContext('2d');
      var image = new Image();
      image.onload = function () {
        inputContext.drawImage(image, 0, 0);
      };
      image.src = base64;

      const context = document.getElementById('output-canvas').getContext('2d');
      context.drawImage(state['qr_crop'], 0, 0);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="my-5">
        <Container>
          <h4>Playground</h4>
          <Form.Control value={base64} onChange={(e) => setBase64(e.target.value)} as="textarea" rows={4} />
          <div className="mt-2 mb-5">
            <Button onClick={clicked}>Submit</Button>
          </div>

          <h4>Input</h4>
          <canvas style={{border: "1px solid black"}} height="512" width="512" id="input-canvas"></canvas>

          <h4>Output</h4>
          <canvas style={{border: "1px solid black"}} height="512" width="512" id="output-canvas"></canvas>
        </Container>
      </main>
    </div>
  )
}
