import Head from 'next/head'
import Header from '../src/components/Header'
import styles from '../styles/Home.module.css'
import Webcam from 'react-webcam';
import { useEffect, useRef, useState } from 'react';
import { PipelineBuilder } from '../src/utils/Pipeline';
import { Container } from 'react-bootstrap';
const CAMERA_DIMENSION = 500;

let pipeline;
export default function Predict() {
  const webcamRef = useRef(null);
  const initializePipeline = async () => {
    pipeline = await PipelineBuilder.loadFromPath("/configs/abbott.json")
  }
  const makePrediction = async (base64) => {
    const state = { base64 }
    try {
      const { result, reason } = await pipeline.execute(state);
      console.log("Found!");
    } catch (error) {
      console.log("Not found");
    }
  }
  useEffect(() => {
    if (typeof window !== "undefined") {
      initializePipeline();
      setInterval(() => {
        if (pipeline) {
          const base64 = webcamRef.current.getScreenshot();
          makePrediction(base64);  
        }
      }, 1000)
    }
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Predict</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container style={{maxWidth: "560px"}} className="py-4 px-4" id="self-checkout">
        <h3 className="my-5">Hold the test in front of the camera</h3>
        <div className="mb-4" style={{width: "max-content"}}>
          <div className="camera-wrapper">
            <div className="camera-image-overlay">
              <img src={"/images/abbott/transparent-full-outline-dotted.png"} />
            </div>
            <Webcam
              audio={false}
              ref={webcamRef}
              screenshotFormat="image/jpeg"
              videoConstraints={{
                width: CAMERA_DIMENSION,
                height: CAMERA_DIMENSION,
                facingMode: "environment"
              }}
              style={{ cursor: "pointer" }}
            />
            <div className="clearfix"></div>
          </div>
        </div>
      </Container>
    </div>
  )
}