import Head from 'next/head'
import { useRouter } from 'next/router';
import Quality from '../../../src/devices/Quality'

export default function Home() {
  const { query, isReady } = useRouter();

  if (!isReady) {
    return <></>
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <Quality uid={query.uid} />
      </main>
    </div>
  )
}
